# serene v3.2.0
#
# - docs: https://github.com/isunjn/serene/blob/latest/USAGE.md
# - check for updates: https://github.com/isunjn/serene/releases
#
#=========================================================================================


# The URL the site will be built for
base_url = "https://darkaine.fr"

author = "Darkaine"
title = "Partager pour mieux comprendre et apprendre"
description = "Je partage mes notes et mémos sur ce que j'apprends et découvre"
default_language = "fr"
theme = "serene"

output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false            # Keep this false, search is temporarily unsupported
generate_feeds = true                 # Whether to generate a feed file in root, read docs for more info about rss feed
feed_filenames = ["feed.xml"] 
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
    { theme = "serene-light", filename = "hl-light.css"},
    { theme = "serene-dark", filename = "hl-dark.css"},
]
render_emoji = true
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

name = "Mémos"                     # Your name
id = "Mémos"                           # Your id / username / handle
bio = "Receuil de notes et espace de partage"                          # Your bio
avatar = "img/apple-touch-icon.png"            # Your avatar
links = [                             # Your links
    {name = "GitHub", icon = "github", url = "https://github.com/drkaine/darkaine"},
]

homepage_layout = "recent"             # "about" | "list" | "recent"

recent_max = 15
recent_more = true
recent_more_text = "plus »"

sections = [
    { name = "Notes", path = "/notes", is_external = false },
    { name = "Participer", path = "/participer", is_external = false },
    { name = "Projets", path = "/projects", is_external = false },
    #{ name = "github", path = "https://github.com/drkaine", is_external = true },
]
blog_section_path = "notes"

nav_separator = "  =>  "
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

display_id = true                     # Whether to display your id on homepage
blog_categorized = true               # Whether to categorize blog posts
blur_effect = true                    # Whether to turn on blur effect on navigation bar
back_to_top = true                    # Whether to show back-to-top button on post pages

toc = true                            # Whether to show Table-Of-Contents by default
copy = true                           # Whether to add a copy button on code blocks by default
comment = true                        # Whether to show giscus comment section by default, see https://giscus.app for more info
display_tags = true                   # Whether to display tags on post pages by default
truncate_summary = false              # Whether to truncate the summary of a post by default

progress_bar = true              # Whether to show reading progress bar
cc_license = true               # Whether to show Creative-Commons statement [Can be overridden by page config]
cc_license_statement = "Ce travail est sous licence [CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/)."  # The Creative-Commons statement

outdate_alert = true                 # Whether to show outdate alert by default
outdate_alert_days = 120              # How many days will a post be outdated by default
outdate_alert_text_before = "Note: Cet article a été mis à jour pour la dernière fois il y a "
outdate_alert_text_after = " jours et pourrait ne plus être à jour."

footer_copyright = "© 2024 Darkaine"
footer_credits = true                 # Whether to show "powered by zola and serene" in footer

not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« Retour à l'accueil »"
force_theme = false
reaction = false
