[[project]]
author = "Darkaine"
name = "darkaine"
desc = "Blog ouvert à tous pour partager des notes, des articles, des tutoriaux, etc."
tags = ["blog"]
img = ""
links = [
  { name = "Site", url = "https://darkaine.fr" },
]
